from abc import ABC, abstractmethod


# Official docs concept:
# Python's abc module supports abstract base classes. @abstractmethod marks a
# method that subclasses must implement before they can be instantiated.
# Docs: https://docs.python.org/3/library/abc.html
#
# Our project significance:
# OtpService depends on this interface, not a concrete sender. That is what lets
# us keep the OTP logic unchanged while swapping delivery from console mock to
# the new WhatsApp Web HTTP sender.
#
# OtpSender is the delivery abstraction for OTP messages.
#
# Why this exists:
# OtpService should own OTP business logic:
# - generate OTP
# - hash OTP
# - store expiry/cooldown/attempt data
# - verify submitted OTP
#
# It should not care whether the OTP is delivered by:
# - console print during development
# - WhatsApp Web sender service
# - SMS provider
# - email provider
#
# This interface gives OtpService one stable method to call: send_otp(...).
class OtpSender(ABC):
    # Official docs concept:
    # Abstract methods define the required shape of subclasses.
    #
    # Our project significance:
    # MockOtpSender and WhatsappHttpSender must both accept sender_phone,
    # receiver_phone, and otp keyword arguments and return None after delivery.
    # OtpService can call either one without branching on sender type.
    #
    # Every concrete sender must implement this method.
    #
    # The method is async because real senders usually perform I/O:
    # - HTTP request to another service
    # - network call to SMS/WhatsApp provider
    # - database/event queue write
    #
    # sender_phone:
    #   The selected sender identity. WhatsApp mode uses this to choose the
    #   registered whatsapp-web.js session. Mock mode only prints it.
    #
    # receiver_phone:
    #   The user phone number that should receive the OTP.
    #
    # otp:
    #   The raw 6-digit OTP generated by OtpService.
    @abstractmethod
    async def send_otp(
        self,
        *,
        sender_phone: str,
        receiver_phone: str,
        otp: str,
    ) -> None:
        pass
