from app.senders.base import OtpSender


# Official docs concept:
# This class implements the abstract send_otp(...) method required by OtpSender.
# Python allows normal concrete subclasses once all abstract methods are present.
#
# Our project significance:
# MockOtpSender is the safest sender for local backend testing because it does
# not contact WhatsApp and does not require a QR-linked device. It lets Swagger
# UI tests validate OTP generation, hashing, cooldown, max attempts, and reuse
# prevention before WhatsApp delivery is introduced.
#
# MockOtpSender is the development sender.
#
# It does not call WhatsApp, SMS, or any external provider. It only prints the
# OTP to the backend console so the developer can manually copy it into Swagger
# or another API client while testing /otp/request and /otp/verify.
#
# Why it is still useful after adding WhatsApp:
# - lets us test OTP generation/verification without a WhatsApp login
# - avoids sending real messages during backend-only development
# - gives a safe fallback mode if the WhatsApp Web session is disconnected
class MockOtpSender(OtpSender):
    # Match the OtpSender interface exactly.
    #
    # sender_phone:
    #   The selected sender value from the API request. Mock mode does not need
    #   a real WhatsApp session, but printing it helps confirm the API contract
    #   is being passed correctly.
    #
    # receiver_phone:
    #   The receiver phone value from the API request.
    #
    # otp:
    #   The raw OTP generated by OtpService. This is printed only in mock mode.
    #   The database stores a hash, not this raw value.
    async def send_otp(
        self,
        *,
        sender_phone: str,
        receiver_phone: str,
        otp: str,
    ) -> None:
        print(
            "[MOCK OTP] "
            f"sender_phone={sender_phone} receiver_phone={receiver_phone} otp={otp}"
        )
