import httpx

from app.config import settings
from app.senders.base import OtpSender


# Official docs concept:
# httpx is an HTTP client for Python with both sync and async APIs. AsyncClient
# is used when making HTTP requests from async code so the event loop is not
# blocked while waiting for network I/O.
# Docs: https://www.python-httpx.org/async/
#
# Our project significance:
# FastAPI route handlers and OtpService methods are async. The WhatsApp sender
# service is a separate local Node/Express process, so the Python backend needs
# to call it over HTTP without blocking the whole API server.


# Custom exception for WhatsApp sender delivery failures.
#
# Why create our own exception:
# httpx has several low-level exception types:
# - HTTPStatusError when the server responds with a 4xx/5xx status
# - RequestError when the request cannot be completed at all
#
# OtpService should not need to know those HTTP-client details. This exception
# gives the backend one app-specific error type for "the WhatsApp delivery layer
# failed".
class WhatsappSenderError(Exception):
    # Store structured sender-failure information.
    #
    # status_code:
    #   HTTP status FastAPI should return to its own caller.
    #
    # error_code:
    #   Machine-readable code from the Node sender service when available, such
    #   as "number_not_registered" or "sender_not_ready".
    #
    # message:
    #   Human-readable explanation safe to return in local POC API responses.
    def __init__(self, *, status_code: int, error_code: str, message: str) -> None:
        super().__init__(message)
        self.status_code = status_code
        self.error_code = error_code
        self.message = message


# WhatsappHttpSender is the Python adapter that connects OtpService to the
# local Node whatsapp-web.js sender service.
#
# Official docs concept:
# This class implements the abstract send_otp(...) method required by OtpSender.
# Python's abc module requires concrete subclasses to implement abstract methods
# before they can be instantiated.
#
# Our project significance:
# OtpService already calls:
#   await self.sender.send_otp(
#       sender_phone=sender_phone,
#       receiver_phone=phone,
#       otp=otp,
#   )
#
# Because WhatsappHttpSender has the same method shape as MockOtpSender, main.py
# can switch between mock and WhatsApp delivery through configuration without
# changing OTP generation, hashing, cooldown, expiry, or verification logic.
class WhatsappHttpSender(OtpSender):
    # Send one OTP through the Node WhatsApp sender service.
    #
    # Input contract:
    # sender_phone:
    #   E.164-style string identifying the authenticated WhatsApp sender
    #   session, for example:
    #     "+918637427358"
    #
    # receiver_phone:
    #   E.164-style string identifying the user/receiver, for example:
    #     "+919876543210"
    #
    # otp:
    #   Six-digit OTP string generated by OtpService, for example:
    #     "123456"
    #
    # Output contract:
    #   Return None when delivery succeeds.
    #   Raise WhatsappSenderError when delivery fails.
    #
    # Why return None:
    # OtpService currently cares only whether the send operation succeeded or
    # failed. It does not need the WhatsApp message id to verify OTPs.
    async def send_otp(
        self,
        *,
        sender_phone: str,
        receiver_phone: str,
        otp: str,
    ) -> None:
        # Build the Node sender endpoint URL.
        #
        # settings.whatsapp_sender_url default:
        #   http://127.0.0.1:3001
        #
        # Node route:
        #   POST /send-otp
        #
        # rstrip("/") prevents accidental double slashes if a developer sets:
        #   WHATSAPP_SENDER_URL=http://127.0.0.1:3001/
        #
        # Both configs produce:
        #   http://127.0.0.1:3001/send-otp
        url = f"{settings.whatsapp_sender_url.rstrip('/')}/send-otp"

        # Header required by the Node sender service.
        #
        # Node index.js checks this header in requireSenderApiKey(...):
        #   X-SENDER-API-KEY: local-dev-key
        #
        # Project significance:
        # /send-otp sends real WhatsApp messages. Even for a local POC, we do not
        # want unauthenticated local requests to trigger message sending.
        headers = {
            "X-SENDER-API-KEY": settings.whatsapp_sender_api_key,
        }

        # JSON body expected by the Node /send-otp endpoint.
        #
        # This exactly matches the contract tested manually with PowerShell:
        #   {
        #     "sender_phone": "+918637427358",
        #     "receiver_phone": "+919876543210",
        #     "otp": "123456"
        #   }
        #
        # Node then validates:
        # - sender_phone is E.164-style and registered/ready
        # - receiver_phone is E.164-style
        # - otp is exactly six digits
        # - receiver number is registered on WhatsApp
        payload = {
            "sender_phone": sender_phone,
            "receiver_phone": receiver_phone,
            "otp": otp,
        }

        # Official docs concept:
        # HTTP clients should use timeouts so requests do not wait forever.
        # httpx.Timeout(...) configures timeout behavior for the request/client.
        # Docs: https://www.python-httpx.org/advanced/timeouts/
        #
        # Our project significance:
        # If the Node sender service is not running, WhatsApp Web is stuck, or
        # the local HTTP call hangs, /otp/request should fail in a bounded amount
        # of time instead of leaving the API request open indefinitely.
        timeout = httpx.Timeout(settings.whatsapp_sender_timeout_seconds)

        # Official docs concept:
        # AsyncClient is used as an async context manager so resources such as
        # network connections are properly opened and closed.
        #
        # Our project significance:
        # This keeps the adapter simple and safe for the POC. Each OTP send gets
        # a short-lived HTTP client with the configured timeout.
        async with httpx.AsyncClient(timeout=timeout) as client:
            try:
                # Send the POST request to the Node sender.
                #
                # httpx json=payload behavior:
                # - serializes the Python dict as JSON
                # - sets the request body
                # - sends the appropriate JSON content type
                #
                # Expected successful Node response:
                #   {
                #     "sent": true,
                #     "to": "919876543210@c.us",
                #     "messageId": "..."
                #   }
                response = await client.post(
                    url,
                    headers=headers,
                    json=payload,
                )

                # Official docs concept:
                # response.raise_for_status() raises HTTPStatusError for 4xx or
                # 5xx responses and does nothing for 2xx responses.
                #
                # Our project significance:
                # The Node sender already maps expected failures to HTTP status:
                # - 400 invalid phone/OTP
                # - 401 invalid API key
                # - 404 number not registered
                # - 503 WhatsApp not ready
                #
                # raise_for_status() lets this adapter treat any of those as a
                # failed delivery.
                response.raise_for_status()
            except httpx.HTTPStatusError as exc:
                # The Node service responded, but it responded with an error
                # status. Preserve its structured JSON error when available so
                # FastAPI can return clear failure information to Flutter/manual
                # testers.
                try:
                    error_body = exc.response.json()
                except ValueError:
                    error_body = {}

                raise WhatsappSenderError(
                    status_code=exc.response.status_code,
                    error_code=error_body.get("error", "whatsapp_sender_error"),
                    message=error_body.get(
                        "message",
                        "WhatsApp sender returned an error.",
                    ),
                ) from exc
            except httpx.RequestError as exc:
                # RequestError covers connection-level failures:
                # - connection refused because Node service is stopped
                # - DNS/network errors
                # - timeout
                #
                # In this POC, the most common cause will be forgetting to run:
                #   cd whatsapp-sender
                #   npm start
                raise WhatsappSenderError(
                    status_code=503,
                    error_code="whatsapp_sender_unavailable",
                    message=f"Could not reach WhatsApp sender service: {exc}",
                ) from exc
